services:
  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile.book
    container_name: book-service
    ports:
      - "8000:8000"

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile.review
    container_name: review-service
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - book-service
      - review-service
