
services:
  db:
    image: postgres:15
    container_name: books-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booksdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d booksdb"]  # Added database name
      interval: 5s
      retries: 10  # Increased retries
      timeout: 5s
      start_period: 10s

  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: booksdb
    restart: unless-stopped

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8002:8000"
    depends_on:
      db:
        condition: service_healthy
      book-service:  # Add dependency on book-service
        condition: service_started
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: booksdb
    restart: unless-stopped
  
  

volumes:
  db_data: